//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int IdMaterial { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> MinCount { get; set; }
        public Nullable<int> CountInBox { get; set; }
        public string Unit { get; set; }
    }
}
