//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSuppliers
    {
        public int IdMaterialSuppliers { get; set; }
        public string Material { get; set; }
        public string Supplier { get; set; }
    }
}
