//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int IdSuppliers { get; set; }
        public string Name { get; set; }
        public string TypeSuppliers { get; set; }
        public string INN { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> DateStartWork { get; set; }
    }
}
